module.exports = {
    BASE_URL: "https://kidthink.ca",
    G_FORM_API_KEY: "Y2tfOWQ2MmE2NTU5MWI5Y2M1NjZiY2I0ODk4NzA5YTIxODIyNTRmZWUwZTpjc18xZjMwNmJmNzJjNWFjYzI1ZGU1NmFiOTlmZjkxNDlkMzg2ODk0NGQ3",
    QUESTIONS_FORM_ID: '16',
    CONTACT_FORM_ID: '17',
    SUBMIT_ANONIMOUS: true,
}